#!/usr/bin/env perl
# vim:ts=4:shiftwidth=4:noexpandtab:smartindent

use strict;
use warnings;

open(my $fh, "<", "badpixel.bin") or die $!;

my $buf;
while (sysread($fh, $buf, 2)==2) {
	my ($x_dat) = unpack("v", $buf);

	my $x = $x_dat & 0x1fff;
	my $xcnt = ($x_dat>>13) & 7;

	while ($xcnt>=0) {
		sysread($fh, $buf, 2)==2 or die "lost sync";
		my ($y_dat) = unpack("v", $buf);

		my $y = $y_dat & 0x1fff;
		my $ycnt = ($y_dat>>13) & 7;

		while ($ycnt>=0) {
			print "$x $y 0\n";
			$y++;
			$ycnt--;
		}
		$xcnt--;
	}
}

=head1 SEE ALSO

L<https://github.com/mpetroff/chdk-elph330hs/blob/master/modules/dng.c#L909>
